name: SAST with Semgrep

permissions: {}

on:
  workflow_call:
    outputs:
      sha256:
        description: The sha256 of the file with the results of the SAST
        value: ${{ jobs.sast.outputs.sha256 }}
jobs:
  sast:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      sha256: ${{ steps.set-output.outputs.sha256 }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - shell: bash
        run: |
          python3 -m pip install semgrep
          semgrep ci 2>&1 | tee sast.txt
        env:
          SEMGREP_RULES: p/default
      - id: upload
        uses: slsa-framework/slsa-github-generator/.github/actions/secure-upload-artifact@main
        with:
          name: sast.txt
          path: sast.txt
        if: ${{ always() }}
      - id: set-output
        run: echo "sha256=${{ steps.upload.outputs.sha256 }}" >> $GITHUB_OUTPUT
